### ISSUE TITLE
Browser can't spawn on Synology

### ISSUE THREAD

**Issue by theo-basty** [ThePhaseless/Byparr#3]
Hey ! Thank you for your project !

I'm trying to use it with the arr suit with the latest container image but I have an issue.
When I try to get a challenge check, I end up with the following error :
```
flaresolverr-byparr-1  | INFO:     Request: cmd='request.get' url='https://www.ygg.re/engine/search?category=2145&do=search&order=desc&sort=publish_date' maxTimeout=60000
flaresolverr-byparr-1  | INFO:     192.168.20.9:59132 - "POST /v1 HTTP/1.1" 500 Internal Server Error
flaresolverr-byparr-1  | ERROR:    Exception in ASGI application
flaresolverr-byparr-1  | Traceback (most recent call last):
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
flaresolverr-byparr-1  |     result = await app(  # type: ignore[func-returns-value]
flaresolverr-byparr-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
flaresolverr-byparr-1  |     return await self.app(scope, receive, send)
flaresolverr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
flaresolverr-byparr-1  |     await super().__call__(scope, receive, send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
flaresolverr-byparr-1  |     await self.middleware_stack(scope, receive, send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
flaresolverr-byparr-1  |     raise exc
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
flaresolverr-byparr-1  |     await self.app(scope, receive, _send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
flaresolverr-byparr-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
flaresolverr-byparr-1  |     raise exc
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
flaresolverr-byparr-1  |     await app(scope, receive, sender)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
flaresolverr-byparr-1  |     await self.middleware_stack(scope, receive, send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
flaresolverr-byparr-1  |     await route.handle(scope, receive, send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
flaresolverr-byparr-1  |     await self.app(scope, receive, send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
flaresolverr-byparr-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
flaresolverr-byparr-1  |     raise exc
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
flaresolverr-byparr-1  |     await app(scope, receive, sender)
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
flaresolverr-byparr-1  |     response = await func(request)
flaresolverr-byparr-1  |                ^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
flaresolverr-byparr-1  |     raw_response = await run_endpoint_function(
flaresolverr-byparr-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
flaresolverr-byparr-1  |     return await dependant.call(**values)
flaresolverr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/main.py", line 33, in read_item
flaresolverr-byparr-1  |     browser = await new_browser()
flaresolverr-byparr-1  |               ^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/src/utils/browser.py", line 30, in new_browser
flaresolverr-byparr-1  |     return await webdriver.start(config=config)
flaresolverr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/nodriver/core/util.py", line 88, in start
flaresolverr-byparr-1  |     return await Browser.create(config)
flaresolverr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/nodriver/core/browser.py", line 91, in create
flaresolverr-byparr-1  |     await instance.start()
flaresolverr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/nodriver/core/browser.py", line 351, in start
flaresolverr-byparr-1  |     raise Exception(
flaresolverr-byparr-1  | Exception:
flaresolverr-byparr-1  |                 ---------------------
flaresolverr-byparr-1  |                 Failed to connect to browser
flaresolverr-byparr-1  |                 ---------------------
flaresolverr-byparr-1  |                 One of the causes could be when you are running as root.
flaresolverr-byparr-1  |                 In that case you need to pass no_sandbox=True
```

Hope that it can help with finding any issue !

**Comment by skyless** [comment]
Same here on Synology. Exactly what I have too with building https://github.com/21hsmw/FlareSolverr.git#nodriver-support too.

**Comment by ThePhaseless** [comment]
Hi, thanks for the issue and info, but unfortunately I use a pc as my server, so I can't replicate. @theo-basty What device are you using? Anyway I think this is the issue with the nodriver itself rather than this project. If you have some time and want to help, you could try the steps I just added to README

**Comment by theo-basty** [comment]
I'm running it in a headless Ubuntu vm without graphics server. I've quickly checked the troubleshooting steps. I will try them in some time to see if I can give you more info on that.

**Comment by skyless** [comment]
Issue with nodriver for sure: https://github.com/ultrafunkamsterdam/nodriver/blob/1bb6003c7f0db4d3ec05fdf3fc8c8e0804260103/nodriver/core/browser.py#L352

I wanted to open an issue there but "An owner of this repository has limited the ability to open an issue to users that are collaborators on this repository."

As I still don't know what's wrong exactly, I was hoping to find some help here too. :)

**Comment by skyless** [comment]
Just found out about it on reddit: https://www.reddit.com/r/webscraping/comments/1e14iqx/nodriver_with_docker/

=> https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1358

**Comment by ThePhaseless** [comment]
I'll look into that, thx

**Comment by skyless** [comment]
@ThePhaseless Don't hesitate to ask for some tests if needed once you have a branch with a potential fix. :)

**Comment by ThePhaseless** [comment]
Hey, Hi! I've remade the base for container, could you check now please? @skyless @theo-basty

**Comment by skyless** [comment]
And here's the ping from prowlarr:

```
INFO:     Request: cmd='request.get' url='https://prowlarr.servarr.com/v1/ping' maxTimeout=60000

INFO:     172.17.0.1:47822 - "POST /v1 HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    return await self.app(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app

    response = await func(request)

               ^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app

    raw_response = await run_endpoint_function(

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function

    return await dependant.call(**values)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/main.py", line 33, in read_item

    browser = await new_browser()

              ^^^^^^^^^^^^^^^^^^^

  File "/app/src/utils/browser.py", line 31, in new_browser

    return await webdriver.start(config=config)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/nodriver/core/util.py", line 88, in start

    return await Browser.create(config)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/nodriver/core/browser.py", line 91, in create

    await instance.start()

  File "/app/.venv/lib/python3.12/site-packages/nodriver/core/browser.py", line 351, in start

    raise Exception(

Exception: 

                ---------------------

                Failed to connect to browser

                ---------------------

                One of the causes could be when you are running as root.

                In that case you need to pass no_sandbox=True 
```

**Comment by ThePhaseless** [comment]
Hmm... This could be a problem with docker host, could you expose port 5900 and check with novnc and check if chromium is starting? Or could you try another host? Trying to eliminate as much problems as possible. My both arm64 and x64 as well as github actions do work, so I suspect this could be related to some docker permissions or sth

**Comment by skyless** [comment]
It works great locally (build + run) on my mac M1 chip... (and ygg.re challenge works too) :'(

Definitively agree with docker issue but this is the only one container I can't run properly on my Synology yet. Still searching how to resolve it (will try novnc check asap).

**Comment by ThePhaseless** [comment]
Hi, could you check again? I've remade the software and should be more stable.
